### ISSUE TITLE
Can you write in the readme the process to install this?

### ISSUE THREAD

**Issue by vineetkishore01** [mishailovic/Hackintosh-Dell-7567-OpenCore_Monterey#10]
Hi,
Thanks for bringing Sonoma update but I have zero clue how can I upgrade from Ventura to Sonoma? 
I have installed Ventura using this tutorial and is working great for me https://github.com/mishailovic/Hackintosh-Dell-7567-OpenCore_Ventura
How to update to OC 0.9.5 and also use your EFI to install macOS
I tried making a bootable USB but it is not showing the recovery option in the BootPicker.

**Comment by mishailovic** [comment]
Frankly I didn't bring Sonoma update yet. There is no instructions on Dortania for that (yet?)

**Comment by vineetkishore01** [comment]
https://github.com/mavethee/Hackintosh-OpenCore-EFI-DELL-7567 
can you check this and see if you can explain how to update? 
also why did you leave the telegram group? Come back bro

**Comment by mishailovic** [comment]
> https://github.com/mavethee/Hackintosh-OpenCore-EFI-DELL-7567 can you check this and see if you can explain how to update? also why did you leave the telegram group? Come back bro

I'm not sure I have any free time for that, but I'll try to figure it out. Stay tuned 🤙

**Comment by vineetkishore01** [comment]
Absolutely sir, thank you very much. Would be looking forward to it.

**Comment by mishailovic** [comment]
Ok, well, after some look inside repo you've sent, I think all you have to do is change EFI folder frome mine to what's inside this repo and update via settings, should work

**Comment by mishailovic** [comment]
Don't forget to back up all your files of course, no one's responsible for loss. And let me know if you have any progress in this, that's would be really helpful because I sold mine 7567 and work on EFI "blindly"

**Comment by mishailovic** [comment]
And one more thing: note that WiFi kext isn't available for sonoma yet, this is applied only if you have an intel WiFi card

**Comment by vineetkishore01** [comment]
Hi bro, it has been a long time. I know you've deleted your telegram account and moved out but many of us are still using our Dell 7567. Is there any chance you could provide a pre-built EFI with USBMAPs (since most of us are not so technically equipped to do it ourselves) and provide a proper installation method like you did with Ventura. Many of us are still using it and are stuck on it forever. Please help is you can.

**Comment by vineetkishore01** [comment]
For the WIFI kext, we will use Heliport no worries.

**Comment by mishailovic** [comment]
There is nothing I can do, I’m afraid to say… I sold this laptop a while ago, since I use my iPad mostly for work. There’s really detailed tutorial on how to build efi: https://dortania.github.io/OpenCore-Install-Guide/ 

I used to make an efi build, and it also has usb mapping covered.

**Comment by mishailovic** [comment]
Also use the info provided here: https://github.com/mavethee/Hackintosh-OpenCore-EFI-DELL-7567
This user reportedly got Sonoma version to work on dell 7567

**Comment by SirDank** [comment]
@mishailovic I'm trying to port this to Sonoma, I could use your help!
https://github.com/SirDank/Hackintosh-Dell-7567-OpenCore_Sonoma
