### ISSUE TITLE
Should add guide to USB mapping in the Post-install part

### ISSUE THREAD

**Issue by h9419** [mishailovic/Hackintosh-Dell-7567-OpenCore_Monterey#11]
## Should add guide to USB mapping in the Post-install part

The SSDT and drivers are great and saved me a lot of time in configuration. However, the provided USB map does not work for my 7567. 

I'm not asking for you to change the config to use InjectAll, just add a mention so that people using this resources knows where to look when their USB devices does not show up

**Comment by mishailovic** [comment]
Hey 👋. Glad to hear that and sorry that my maps didn't work. I don't really have time to make adjustments to readme, however, prs are welcome. If you know what you are talking about, you can make one and I'll accept it

**Comment by h9419** [comment]
Got it, I may do it when I find the time since injectAll works well enough for now. Appreciate your work

**Comment by mishailovic** [comment]
I'll close issue when readme will be added with requested information

**Comment by h9419** [comment]
@mishailovic I created the PR https://github.com/mishailovic/Hackintosh-Dell-7567-OpenCore_Ventura/pull/12. Thank you for your time
