### ISSUE TITLE
Bluetooth

### ISSUE THREAD

**Issue by UnknownKriodluk** [mishailovic/Hackintosh-Dell-7567-OpenCore_Monterey#13]
Добавьте инъектор блютуз в config.plist. Вы забыли это сделать

**Add the bluetooth injector to config.plist**. You forgot to do it

**Comment by mishailovic** [comment]
I am using IntelBluetoothFirmware.kext and Bluetooth works fine. Also this project is no longer maintained, but you're more than welcome to send a PR

**Comment by UnknownKriodluk** [comment]
> I am using IntelBluetoothFirmware.kext and Bluetooth works fine. Also this project is no longer maintained, but you're more than welcome to send a PR

My Bluetooth didn't start. It is not defined in the system.
![image](https://github.com/mishailovic/Hackintosh-Dell-7567-OpenCore_Ventura/assets/115110069/b305d179-481b-4766-8ba6-408399ef8d39)

**Comment by UnknownKriodluk** [comment]
I didn't change anything except the serial number

**Comment by mishailovic** [comment]
Yeah, that's probably because you have Broadcom Bluetooth module, which, of course, isn't compatible with Intel .kext. You've probably changed it yourself because I've never seen dell 7567 with Broadcom module out of the box.

**Comment by UnknownKriodluk** [comment]
And Windows defines intel

**Comment by mishailovic** [comment]
Sounds really fishy. Universal solution is just to buy some cheap Bluetooth dongle, which will do better job that built-in

**Comment by UnknownKriodluk** [comment]
Okay, thanks, I'll figure it out somehow.

**Comment by mishailovic** [comment]
Yeah, let me know if you will. Because, apart this opencore build is older than half a year, I've tested it like 1000 times.

**Comment by UnknownKriodluk** [comment]
We need to add this to nvram

7C436110-AB2A-4BBB-A880-FE41995C9F82 -> bluetoothExternalDongleFailed Data 00
7C436110-AB2A-4BBB-A880-FE41995C9F82 -> bluetoothInternalControllerInfo Data 0000000000000000000000000000

**Comment by UnknownKriodluk** [comment]
Then Reset NVRam and everything will work
