### ISSUE TITLE
Nvidia Graphics

### ISSUE THREAD

**Issue by apollotsantos** [mishailovic/Hackintosh-Dell-7567-OpenCore_Monterey#8]
Hi, 

Does nvidia gtx1050TI works on this build?

**Comment by mishailovic** [comment]
Nope, Nvidia kext is broken since Catalina

**Comment by apollotsantos** [comment]
Sorry to bother, is the performance smooth? Compared to Windows...

**Comment by mishailovic** [comment]
> Sorry to bother, is the performance smooth? Compared to Windows...

If your main goal speed and performance - use Windows. Mac OS isn't really a powerhouse.
