### ISSUE TITLE
1050Ti?

### ISSUE THREAD

**Issue by geueds** [mishailovic/Hackintosh-Dell-7567-OpenCore_Monterey#9]
Hey, let me leave this suggestion:

I've just saw [here](https://www.reddit.com/r/hackintosh/comments/vzttfe/gtx_1050_ti_on_macos_monterey_124/) that there's a way to setup the GTX 1050Ti in the Hackintosh, mainly because **there are actual drivers for the graphic card**.

Could you make an optional EFI for that and see if it works?

Thanks!

**Comment by mishailovic** [comment]
Those web drivers are extremely experimental, yet this is the only way to use HDMI on this device. I will definitely take a look at it

**Comment by geueds** [comment]
[Someone else who made it](https://www.reddit.com/r/hackintosh/comments/13rwuof/gtx_1050ti_on_macos_ventura_134/) :)

Thanks!

**Comment by xmb9** [comment]
Unfortunately, these drivers do not seem to support any mobile NVIDIA GPUs. They only support desktop NVIDIA cards.
